BASEPATH=.

BUILD_NDK_VERSION_NO=19.2.5345600

BUILD_HOST=~/Android/Sdk/ndk/$BUILD_NDK_VERSION_NO/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21
NDKPATH=~/Android/Sdk/ndk/$BUILD_NDK_VERSION_NO/
CMAKEPATH=~/Android/Sdk/cmake/3.18.1/bin

PLATFORM=arm64-v8a
BUILDTYPE=Debug

CURRENT_BOOST_ROOT_PATH=~/Downloads/someip/19/$PLATFORM
CURRENT_BOOST_VERSION=boost_1_74
CURRENT_BOOST_VERSION_NO=107400

rm -rf CMakeCache.txt
rm -rf CMakeFiles
rm -rf cmake_install.cmake
rm -rf Makefilu:wqe
rm -rf CTestTestfile.cmake

${CMAKEPATH}/cmake \
	-DCMAKE_TOOLCHAIN_FILE=${NDKPATH}/build/cmake/android.toolchain.cmake \
	-DANDROID_ABI=${PLATFORM} \
	-DANDROID_NDK=${NDKPATH} \
	-DANDROID_NATIVE_API_LEVEL=21 \
	-DANDROID_PLATFORM=android-21 \
	-DANDROID_STL=c++_shared \
	-DCMAKE_BUILD_TYPE=${BUILDTYPE} \
	-DANDROID_TOOLCHAIN=clang \
	-DCMAKE_C_COMPILER=${BUILD_HOST}-clang \
	-DCMAKE_CXX_COMPILER=${BUILD_HOST}-clang++ \
	-DBOOST_ROOT=$CURRENT_BOOST_ROOT_PATH \
	-DBOOST_INCLUDEDIR=$CURRENT_BOOST_ROOT_PATH/include/$CURRENT_BOOST_VERSION \
	-DBOOST_LIBRARYDIR=$CURRENT_BOOST_ROOT_PATH/lib \
	-DBoost_INCLUDE_DIR=$CURRENT_BOOST_ROOT_PATH/include/$CURRENT_BOOST_VERSION \
	-DBoost_LIBRARY_DIR=$CURRENT_BOOST_ROOT_PATH/lib \
	-DBoost_VERSION=$CURRENT_BOOST_VERSION_NO \
	-DCMAKE_INSTALL_PREFIX=${BASEPATH}/out/ \
	-DENABLE_COMPAT=1 \
	-DVSOMEIP_INSTALL_ROUTINGMANAGERD=ON \
	-DENABLE_MULTIPLE_ROUTING_MANAGERS=1 \
	${BASEPATH}
make VERBOSE=1
make install
set +x
